// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sanatorio.Models;

namespace Proyecto.Migrations
{
    [DbContext(typeof(SanatorioContext))]
    [Migration("20201120225103_initialCommit")]
    partial class initialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("Sanatorio.Models.Autoridad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreYApellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RolAutoridad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Autoridad");
                });

            modelBuilder.Entity("Sanatorio.Models.Medico", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreYApellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RolEnEspecialidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("Sanatorio.Models.ObraSocial", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Nombre");

                    b.ToTable("ObraSocial");
                });

            modelBuilder.Entity("Sanatorio.Models.Servicio", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Nombre");

                    b.ToTable("Servicio");
                });

            modelBuilder.Entity("Sanatorio.Models.Usuario", b =>
                {
                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Mail");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
